name: xzdart
version: 0.1.0
description:
  A command-line application that displays examples of execution for Exercism's Dart exercises
# homepage: https://www.example.com
# repository:

executables:
  xzdart: xzdart

publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  args: ^2.3.1
  xzdart_solutions:
    path: packages/xzdart_solutions
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
